import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Camera,Car,Check,ChevronLeft,LocateFixed,MapPin,ParkingCircle,Timer,X}from'lucide-react';import'./style.css';
const read=f=>new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});
function App(){const[flow,setFlow]=useState(false),[step,setStep]=useState(0),[car,setCar]=useState(null),[sign,setSign]=useState(null),[mark,setMark]=useState(null),[pos,setPos]=useState(null),[geo,setGeo]=useState(''),[left,setLeft]=useState(7200),[running,setRunning]=useState(false);
useEffect(()=>{if(!running)return;const t=setInterval(()=>setLeft(x=>Math.max(0,x-1)),1000);return()=>clearInterval(t)},[running]);
const photo=async(e,setter,next)=>{const f=e.target.files?.[0];if(!f)return;setter(await read(f));next&&setStep(next)};
const location=()=>{setGeo('Hämtar plats…');navigator.geolocation?.getCurrentPosition(p=>{setPos({lat:p.coords.latitude,lng:p.coords.longitude,acc:Math.round(p.coords.accuracy)});setGeo('')},()=>setGeo('Platsen kunde inte hämtas. Kontrollera telefonens tillstånd.'),{enableHighAccuracy:true,timeout:10000})};
const start=()=>{setStep(0);setCar(null);setSign(null);setMark(null);setPos(null);setFlow(true)};const time=`${String(Math.floor(left/3600)).padStart(2,'0')}:${String(Math.floor(left%3600/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;
return <div className="app"><header><span className="logo"><ParkingCircle/></span><span><b>Park Check</b><small>Parkera med bättre koll</small></span><button className="icon" onClick={start}><Camera/></button></header><main><p className="muted">God förmiddag</p><h1>Får du parkera här?</h1><p className="lead">Fota bilen och skylten. Bekräfta sedan platsen.</p><button className="primary" onClick={start}><Camera/>Kontrollera parkering</button><div className="three"><span>1<small>Fota bilen</small></span><span>2<small>Markera bilen</small></span><span>3<small>Fota skylten</small></span></div>{running?<section className="timer"><Timer/><p>Tid kvar</p><strong>{time}</strong><small>Exempelparkering · påminnelse 15 minuter innan</small><button className="secondary" onClick={()=>setRunning(false)}>Avsluta parkering</button></section>:<section className="card"><MapPin/><div><b>Ingen aktiv parkering</b><small>Starta en kontroll för att prova hela flödet.</small></div></section>}</main>
{flow&&<div className="flow"><div className="top"><button className="icon" onClick={()=>step?setStep(step-1):setFlow(false)}>{step?<ChevronLeft/>:<X/>}</button><small>{step+1} av 5</small><i/></div><div className="bar"><i style={{width:`${(step+1)*20}%`}}/></div><div className="body">
{step===0&&<><h2>Fota bilen och platsen</h2><p>Se till att hela bilen och vägkanten syns.</p><label className="camera">{car?<img src={car}/>:<><Car/><span>Öppna kameran</span></>}<input type="file" accept="image/*" capture="environment" onChange={e=>photo(e,setCar,1)}/></label><label className="primary">Ta bild<input type="file" accept="image/*" capture="environment" onChange={e=>photo(e,setCar,1)}/></label></>}
{step===1&&<><h2>Vilken bil är din?</h2><p>Tryck mitt på din bil i bilden.</p><div className="picture" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setMark({x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100})}}><img src={car}/>{mark&&<span className="marker" style={{left:`${mark.x}%`,top:`${mark.y}%`}}><Check/></span>}</div><button disabled={!mark} className="primary" onClick={()=>setStep(2)}>Detta är min bil</button></>}
{step===2&&<><h2>Fota hela skylten</h2><p>Ta med huvudskylten och alla mindre skyltar.</p><label className="camera">{sign?<img src={sign}/>:<><ParkingCircle/><span>Öppna kameran</span></>}<input type="file" accept="image/*" capture="environment" onChange={e=>photo(e,setSign,3)}/></label><label className="primary">Ta bild<input type="file" accept="image/*" capture="environment" onChange={e=>photo(e,setSign,3)}/></label></>}
{step===3&&<><h2>Bekräfta platsen</h2><p>Telefonen frågar om tillstånd första gången.</p><div className="map"><LocateFixed/>{pos?<><b>Platsen är hittad</b><small>± {pos.acc} meter</small><small>{pos.lat.toFixed(5)}, {pos.lng.toFixed(5)}</small></>:<><b>Ingen plats hämtad</b><small>{geo||'Tryck på knappen nedan'}</small></>}</div>{!pos?<button className="primary" onClick={location}><LocateFixed/>Hämta min plats</button>:<button className="primary" onClick={()=>setStep(4)}>Ja, rätt plats</button>}</>}
{step===4&&<div className="done"><span><Check/></span><h2>Parkering tillåten</h2><p>Demobesked: högst 2 timmar. Bilderna och platsen har hämtats från telefonen.</p><button className="primary" onClick={()=>{setFlow(false);setRunning(true);setLeft(7200)}}>Starta parkering</button><small>Skyltanalysen är fortfarande exempeldata.</small></div>}
</div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
